Added workflow to publish temporary OCI releases from PR
canonical/ceph-containers pull request #26
Opened 2023-09-04 12:53 UTC by UtkarshBhatthere

2023-09-04 14:41 UTC, UtkarshBhatthere commented
Test Comment

2023-09-05 10:38 UTC, UtkarshBhatthere commented
/publish

2023-09-05 10:57 UTC, sabaini requested changes
Hi @UtkarshBhatthere this is great, thanks! 
One small request, I think it'd be worthwhile to have some commentary around use case and usage for publishing temporary ROCKs

2023-09-05 11:15 UTC, UtkarshBhatthere commented
@sabaini I have added description to the git commit, and the PR. The issue link associated to this PR can also be used to discuss this further.

2023-09-05 12:05 UTC, UtkarshBhatthere commented
Since the newly added workflow has a comment based trigger, this needs to go in main before it can be manually triggered.

2023-09-05 13:20 UTC, sabaini approved these changes

2023-09-05 13:20 UTC, merged

2023-09-05 13:20 UTC, sabaini commented
lgtm, thanks