Review README and HACKING files
canonical/ceph-containers pull request #47
Opened 2023-11-23 23:12 UTC by pmatulis

This is a documentation-only review of the `README` and `HACKING` files. 

In the `HACKING` file, things can be improved at a later time by placing links at the bottom of the file (and using a label), as was done in the README file.

2023-11-24 09:22 UTC, sabaini reviewed
One small Q, otherwise lgtm!

2023-11-24 09:22 UTC, sabaini commented on HACKING.md
> +node ceph cluster for you to tinker with using our image, cephadm and lxd. For
Should we capitalize "Ceph" here?

2023-11-29 09:35 UTC, UtkarshBhatthere commented on README.md
> +| Status | &#x1F7E2; | &#x1F7E1; |
Can you please change this `Status` to `Daemon Status` ?
This was incorrectly mentioned in the original doc and it would be great to fix this here.

2023-11-29 09:37 UTC, UtkarshBhatthere requested changes
Thanks for the change @pmatulis, 2 requests:
1. can you also please rebase your PR with origin/main ? It contains a fix for CI and we'd have a cleaner PR.
2. Inline comment in `README.md`.

2023-11-29 17:35 UTC, merged